#include "gui/embedded_ui.hpp"

// The one TU that includes the generated byte arrays (assets/ is on the
// include path). Drift-guarded by tests/unit/gui_assets_test.cpp: editing
// assets/gui/* requires re-running scripts/embed_gui_assets.py.

#include <cstddef>

#include "embedded_gui_assets.hpp"  // generated; index_data/app_data/style_data

namespace wmr::gui {
namespace {

std::string_view view_of(const unsigned char* data, std::size_t size) {
    return std::string_view(reinterpret_cast<const char*>(data), size);
}

}  // namespace

EmbeddedUi::EmbeddedUi()
    : html(view_of(index_data, index_data_size)),
      js(view_of(app_data, app_data_size)),
      css(view_of(style_data, style_data_size)),
      favicon_svg(view_of(favicon_svg_data, favicon_svg_data_size)),
      favicon_png(view_of(favicon_32_data, favicon_32_data_size)),
      touch_png(view_of(apple_touch_data, apple_touch_data_size)) {}

}  // namespace wmr::gui
