// Copyright 2025 wmr contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef WMR_BUILD_AI_COREML_SD

#include <cstdint>
#include <string>
#include <vector>

#include <opencv2/core.hpp>

namespace wmr {

/**
 * CoreML SDXL img2img pipeline.
 *
 * Native ObjC++ implementation of Stable Diffusion XL base-1.0 running on
 * Apple Silicon via CoreML. Takes a 1024x1024 BGR tile, runs low-strength
 * denoising (1-3 steps) with an empty prompt (CFG guidance=1.0), and returns
 * a regenerated 1024x1024 BGR tile. This is the regen primitive for
 * --synthid-attack regen.
 *
 * Models (converted .mlpackage):
 * - unet: U-Net with 2-step CFG (batch dim fixed at 2). Inputs: sample (2,4,128,128),
 *   timestep (2), encoder_hidden_states (2,2048,1,77). Output: noise_pred (2,4,128,128).
 * - vae_encoder: VAE encoder. Input: x (1,3,1024,1024). Output: latent (1,8,128,128)
 *   = concatenated mean and logvar along channel axis.
 * - vae_decoder: VAE decoder. Input: z (1,4,128,128). Output: image (1,3,1024,1024)
 *   in roughly [-1,1].
 *
 * Text embeddings are pre-baked (empty_prompt_embeds.bin, generated by
 * scripts/gen_coreml_sd_empty_prompt.py) as fp16 (2,2048,1,77). Empty prompt
 * means unconditional CFG, so cond and uncond are identical.
 *
 * Scheduler: CoreMLSDEulerScheduler (see coreml_sd_scheduler.hpp) with SDXL
 * defaults (1000 train timesteps, scaled_linear betas, epsilon prediction).
 *
 * VAE scaling factor: 0.13025 (from vae/config.json). Encode: latent *= 0.13025.
 * Decode: latent /= 0.13025.
 *
 * Usage: initialize() once (loads models + embeds), then img2img() per-tile.
 * Leaked singleton pattern (CoreML teardown races static destruction).
 */
class CoreMLSDPipeline {
public:
    CoreMLSDPipeline();
    ~CoreMLSDPipeline();

    // Initialize pipeline: load models from models_dir and baked embeds from embeds_bin.
    // Returns false if models or embeds not found or load fails.
    bool initialize(const std::string& models_dir, const std::string& embeds_bin);

    // Check if pipeline is ready (models loaded successfully).
    bool is_ready() const;

    // Run img2img denoising on a 1024x1024 BGR tile.
    // strength: 0.0-1.0, lower = less change (typical 0.05-0.15 for weak denoise).
    // steps: number of denoise steps (typical 1-4 for efficiency).
    // seed: RNG seed for reproducible latent noise.
    // Returns 1024x1024 BGR output (regenerated tile).
    cv::Mat img2img(const cv::Mat& tile_bgr, float strength, int steps, uint64_t seed);

private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};

} // namespace wmr

#endif // WMR_BUILD_AI_COREML_SD
