#!/usr/bin/env python3
"""Regenerate assets/embedded_gui_assets.hpp from assets/gui/. Dev-time only
(the generated header is committed; CI and runtime never run Python)."""
import pathlib
root = pathlib.Path(__file__).resolve().parent.parent
out = root / "assets" / "embedded_gui_assets.hpp"
files = {  # fixed order: deterministic. Map: filename -> C++ symbol stem
    "index.html": "index",
    "app.js": "app",
    "style.css": "style",
    "favicon-32.png": "favicon_32",
    "favicon-96.png": "favicon_96",
    "apple-touch-icon.png": "apple_touch",
}
with out.open("w") as f:
    f.write("#pragma once\n// GENERATED by scripts/embed_gui_assets.py; do not edit.\n")
    f.write("// The GUI sources, embedded as byte arrays (spec: served as\n")
    f.write("// separate routes so the CSP stays enforceable).\n")
    f.write("#include <cstddef>\n\nnamespace wmr::gui {\n")
    for name, stem in files.items():
        data = (root / "assets" / "gui" / name).read_bytes()
        sym = stem + "_data"
        f.write(f"inline constexpr unsigned char {sym}[] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(str(b) for b in data[i:i+16]) + ",\n")
        f.write("};\n")
        f.write(f"inline constexpr std::size_t {sym}_size = {len(data)};\n\n")
    f.write("} // namespace wmr::gui\n")
print(f"wrote {out}")
