#pragma once

#include <opencv2/core.hpp>

namespace wmr::antidetect {

// LPIPS restricted to the second AlexNet layer (the AEROBLADE configuration):
// scaling ([-1,1] -> ImageNet norm) -> conv1+relu -> pool1 -> conv2+relu ->
// per-channel spatial unit-normalize -> calibration-weighted squared
// difference, averaged over space.
//
// Used as the adversarial stage's perceptual quality gate (the --lpips-budget
// knob) and by the stage-C report. Weights are embedded at build time
// (assets/lpips_alex_l2.h, generated by experiments/antidetect-eval/
// extract_lpips_weights.py; AlexNet OWT + LPIPS v0.1 calibration, both BSD-3),
// so there is no download and no runtime dependency. Pure TU (OpenCV only).
// Golden-vector regression against the torch reference:
// tests/unit/lpips_alex_test.cpp.
class LpipsAlex {
public:
    // distance between two BGR u8 images of identical size; 0 for identical
    // inputs. Deterministic (pure arithmetic, single-threaded loops).
    float distance(const cv::Mat& a_bgr_u8, const cv::Mat& b_bgr_u8) const;

    // Downscale both inputs so max(h,w) <= max_side, then distance(). The
    // adversarial gate evaluates at reduced resolution (LPIPS averages over
    // space, so this is a fair speed proxy).
    float distance_capped(const cv::Mat& a_bgr_u8, const cv::Mat& b_bgr_u8,
                          int max_side) const;

private:
    // Computes the relu2 feature stack (192 planes, spatially
    // unit-normalized per channel) for one image.
    void features(const cv::Mat& bgr_u8, std::vector<cv::Mat>& out_planes) const;
};

} // namespace wmr::antidetect
